platforms:
  font-face:
    buildPath: dist/css/
    transforms:
    - attribute/font

    files:
      - destination: fonts.css
        format: font-face
        filter:
          attributes:
            category: asset
            type: font
