platforms:
  js:
    buildPath: dist/js/
    transformGroup: js
    prefix: ds
    files:
      - destination: brand-colors.esm.js
        format: javascript/es6
        filter:
            attributes:
              category: color
              type: brand

      - destination: system-colors.esm.js
        format: javascript/es6
        filter:
          attributes:
            category: color
            type: system

      - destination: data-colors.esm.js
        format: javascript/es6
        filter:
          attributes:
            category: color
            type: ramp

      - destination: code-colors.esm.js
        format: javascript/es6
        filter:
          attributes:
            category: color
            type: code
